"""create code chunks

Revision ID: 40d486734ecd
Revises: 891445f29edf
Create Date: 2026-07-27 15:34:32.606716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '40d486734ecd'
down_revision: Union[str, Sequence[str], None] = '891445f29edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('repository_file_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_file_id'], ['repository_files.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_id'), 'code_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_code_chunks_repository_file_id'), 'code_chunks', ['repository_file_id'], unique=False)
    op.create_index(op.f('ix_code_chunks_repository_id'), 'code_chunks', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_chunks_repository_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_repository_file_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_id'), table_name='code_chunks')
    op.drop_table('code_chunks')
    # ### end Alembic commands ###
