"""change embedding dimension to 768

Revision ID: 6230834cd7a2
Revises: be97ad692b7c
Create Date: 2026-07-25 23:32:11.886679

"""

from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa

from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = "6230834cd7a2"
down_revision: Union[str, Sequence[str], None] = "be97ad692b7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "code_chunks",
        "embedding",
        existing_type=VECTOR(dim=384),
        type_=VECTOR(dim=768),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "code_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
