/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedRepositoriesIndexRouteImport } from './routes/_protected/repositories/index'
import { Route as ProtectedRepositoriesRepositoryIdChatRouteImport } from './routes/_protected/repositories/$repositoryId/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRepositoriesIndexRoute =
  ProtectedRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedRepositoriesRepositoryIdChatRoute =
  ProtectedRepositoriesRepositoryIdChatRouteImport.update({
    id: '/repositories/$repositoryId/chat',
    path: '/repositories/$repositoryId/chat',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof ProtectedSettingsRoute
  '/repositories/': typeof ProtectedRepositoriesIndexRoute
  '/repositories/$repositoryId/chat': typeof ProtectedRepositoriesRepositoryIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof ProtectedSettingsRoute
  '/repositories': typeof ProtectedRepositoriesIndexRoute
  '/repositories/$repositoryId/chat': typeof ProtectedRepositoriesRepositoryIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/repositories/': typeof ProtectedRepositoriesIndexRoute
  '/_protected/repositories/$repositoryId/chat': typeof ProtectedRepositoriesRepositoryIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/settings'
    | '/repositories/'
    | '/repositories/$repositoryId/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/settings'
    | '/repositories'
    | '/repositories/$repositoryId/chat'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/settings'
    | '/_protected/repositories/'
    | '/_protected/repositories/$repositoryId/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/repositories/': {
      id: '/_protected/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof ProtectedRepositoriesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/repositories/$repositoryId/chat': {
      id: '/_protected/repositories/$repositoryId/chat'
      path: '/repositories/$repositoryId/chat'
      fullPath: '/repositories/$repositoryId/chat'
      preLoaderRoute: typeof ProtectedRepositoriesRepositoryIdChatRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedRepositoriesIndexRoute: typeof ProtectedRepositoriesIndexRoute
  ProtectedRepositoriesRepositoryIdChatRoute: typeof ProtectedRepositoriesRepositoryIdChatRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedRepositoriesIndexRoute: ProtectedRepositoriesIndexRoute,
  ProtectedRepositoriesRepositoryIdChatRoute:
    ProtectedRepositoriesRepositoryIdChatRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
